### ISSUE TITLE
run failed when using babel-node 

### ISSUE THREAD

**Issue by air-cc** [BiteBit/koa-router-swagger#1]
run failed when I use the module. seems like babel-node can not understand `async` syntax

Error log:
```
> ./node_modules/babel-cli/bin/babel-node.js ./bin/start

/Users/air_cc/workspace/guangfa/ums/node_modules/koa-router-swagger/lib/swagger.js:148
  self.app.use(mount('/api-explorer', async (ctx) => {
                                            ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/air_cc/workspace/guangfa/ums/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/air_cc/workspace/guangfa/ums/node_modules/koa-router-swagger/index.js:3:18)
```

**Comment by BiteBit** [comment]
already fix this.
